### ISSUE TITLE
Error when running the  models

### ISSUE THREAD

**Issue by ColinDean701** [xiachangxue/DeepHyperX#2]
I am a  beginner for DL, when I wanted to run the Hit model for IndianPines,
the error shows 

RuntimeError: Given normalized_shape=[480], expected input with shape [*, 480], but got input of size[2, 8, 8, 400]

I searched in Google and still unable to solve it, can you give some advice？

**Comment by xiachangxue** [comment]
The reason is that the input data has different spectral bands. So, you should give the corrected input, and output, which means that you should modify the kernel size of the patch-projection module. In your experiments, the output of the patch-projection module is 480, however, the output of your data is 400. So, you can modify the Hyperparameters 480 to 400. And you can also modify the kernel size of the PatchEmbed module to extract 480 output features.

Good luck!

**Comment by ColinDean701** [comment]
Very appreciate for your reply。

Good luck!

**Comment by xiachangxue** [comment]
You are welcome! 
Good luck!
